// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as VocabService from "./vocabservice.js";
export {
    VocabService
};

export {
    ProcessResult,
    WordFreq
} from "./models.js";
