// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProcessResult {
    /**
     * Creates a new ProcessResult instance.
     * @param {Partial<ProcessResult>} [$$source = {}] - The source object to create the ProcessResult.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("words" in $$source)) {
            /**
             * @member
             * @type {WordFreq[]}
             */
            this["words"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("words" in $$parsedSource) {
            $$parsedSource["words"] = $$createField1_0($$parsedSource["words"]);
        }
        return new ProcessResult(/** @type {Partial<ProcessResult>} */($$parsedSource));
    }
}

export class WordFreq {
    /**
     * Creates a new WordFreq instance.
     * @param {Partial<WordFreq>} [$$source = {}] - The source object to create the WordFreq.
     */
    constructor($$source = {}) {
        if (!("word" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["word"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WordFreq instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WordFreq}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WordFreq(/** @type {Partial<WordFreq>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WordFreq.createFrom;
const $$createType1 = $Create.Array($$createType0);
