// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ProcessResult {
    "fileName": string;
    "words": WordFreq[] | null;
}

export interface WordFreq {
    "word": string;
    "count": number;
}
